# Automatically generated by configure - do not modify
prefix=/usr/local
bindir=/usr/local/bin
libdir=/usr/local/lib
includedir=/usr/local/include
mandir=/usr/local/man
MAKE=make
CC=gcc
GCC_MAJOR=3
HOST_CC=gcc
AR=ar
STRIP=strip -s -R .comment -R .note
CFLAGS=-O2
LDFLAGS=
ARCH=i386
VERSION=0.9.19
SRC_PATH=/home/foo/tcc_bootstrap_alt/tcc_19
